### ISSUE TITLE
UI rendering issues with Consul v1.15.0

### ISSUE THREAD

**Issue by heikkilamarko** [hashicorp/consul#16429]
After upgrading to Consul `v1.15.0`, we started to see rendering issues in UI. For example, the `Services` page doesn't render all list items when you navigate to the page. After opening the filters (without changing values), the missing items start to come visible. Below are two screenshots. There are 17 services in total, but only some of them are rendered first (screenshot1). After opening the filters, the page start to show all items (screenshot2). As can be seen, there are rendering issues with filters too.

The problem reproduces with latest Chrome, Firefox, and Safari. 

<img width="1053" alt="screenshot1" src="https://user-images.githubusercontent.com/3757314/221371863-6ad32aab-7907-40b2-9a2d-ea4b0dea9815.png">
<img width="1243" alt="screenshot2" src="https://user-images.githubusercontent.com/3757314/221371868-bdf74200-2659-495d-8fd1-5355962da78c.png">

**Comment by krarey** [comment]
I'm seeing this as well in v1.15.0 across several browsers, with variations of the following stack trace in the browser console:
```
Uncaught TypeError: (0 , t.isHTMLSafe) is not a function
    at vendor-9b21ddc3d55dbc248b171f3af693427e.js:8257:23
    at vendor-9b21ddc3d55dbc248b171f3af693427e.js:1209:13
    at Object.getValue (vendor-9b21ddc3d55dbc248b171f3af693427e.js:1209:64)
    at vendor-9b21ddc3d55dbc248b171f3af693427e.js:2998:46
    at vendor-9b21ddc3d55dbc248b171f3af693427e.js:3290:41
    at e.track (vendor-9b21ddc3d55dbc248b171f3af693427e.js:3962:5)
    at m (vendor-9b21ddc3d55dbc248b171f3af693427e.js:3290:20)
    at Object.evaluate (vendor-9b21ddc3d55dbc248b171f3af693427e.js:3617:42)
    at Object.evaluate (vendor-9b21ddc3d55dbc248b171f3af693427e.js:3408:13)
    at Lt.evaluateSyscall (vendor-9b21ddc3d55dbc248b171f3af693427e.js:3710:61)
```

**Comment by elsgaard** [comment]
I am seeing this as well on Ubuntu 22.04 LTS (Jammy Jellyfish) + Chrome Version 110.0.5481.178. After dongrading to 1.14.4 it works correctly again.

**Comment by sid-6581** [comment]
I am seeing the same thing in Vivaldi after upgrading to 1.15.0.

**Comment by marceldegraaf** [comment]
Same issue here. Adding a screenshot of the empty "Overview" page for completeness:

![2023-02-27-08-51-49-O4im38qQ@2x](https://user-images.githubusercontent.com/15011/221505163-9d2842ff-c956-433f-ae58-6e01410c0433.png)

This is on a fresh install of Consul v1.15.0 (revision `53f65dc3`) on a Debian machine (`Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`) with Consul installed from the official Apt repository.

**Comment by ashleykleynhans** [comment]
Also seeing the same issue as in the screenshot above after upgrading my Consul cluster from version 1.14.4 to version 1.15.0.  I attempted to recover the cluster by creating the `raft/peers.json` file on each server node in the cluster and restarting Consul on each, but the problem persists.

**Comment by david-yu** [comment]
Hi folks, we were able to reproduce and fix the issue via https://github.com/hashicorp/consul/pull/16444. This will be back ported and released in 1.15.1 as part of our patch release around mid-march timeframe. Thank you for quick feedback!

**Comment by ashleykleynhans** [comment]
1. Why do you close an issue, when there is no release yet to fix it?
2. Why must we wait weeks for a fix when this is a pretty severe problem, this is UNACCEPTABLE.
3. Why was this release clearly NOT tested before releasing to the public.

Your attitude is unacceptable, and I will not be using any further Hashiscorp products because of it.
Get your act together and ensure that appropriate measures are put in place to stop this from happening again!

**Comment by sid-6581** [comment]
Having to wait several weeks for a bug that makes the UI completely unusable seems a bit wrong to me also, especially when the fix is simple, only affects the UI, and is ready to go. Why not do a hotfix release instead of forcing people to roll back to a previous version?

**Comment by PJDuszynski** [comment]
I don't understand the response when you have a significant component of the program broken in a minor release, have a fix ready, to then decide to wait another 2-3 weeks to release the fix to the users.

**Comment by suikast42** [comment]
> Also seeing the same issue as in the screenshot above after upgrading my Consul cluster from version 1.14.4 to version 1.15.0. I attempted to recover the cluster by creating the `raft/peers.json` file on each server node in the cluster and restarting Consul on each, but the problem persists.

Dude keep clam. 
Hashicrop does a great job. You as a product ownver have to test every release commponenet before going in priduction with it. This inculdes thrid party software like consul or nomad.

If you want have a better support or more stable tested product then make a enterprise subscriptuon on hashicorp. 


Your points here are really not appropriate

**Comment by blake** [comment]
Hi folks,

We understand the frustration around this issue. I’d like to apologize on behalf of our team. This was a miss on our part. We acknowledge that these types of regressions are unacceptable and are taking steps to minimize the possibility of such regressions in the future.

We be publishing a patch release next week which will address these issues. The patch releases will be available no later than March 9th.

**Comment by frh-td** [comment]
1.15.1 fixes the issue on the services and nodes listings, but the cluster overview is still broken with the same error (`TypeError: (0 , n.isHTMLSafe) is not a function`) showing in the console.

![2023-03-08-121819_901x216](https://user-images.githubusercontent.com/73470898/223699956-193ed736-4b6f-476e-a7a1-c18f07bb55c0.png)

**Comment by ahjohannessen** [comment]
Experincing the same as @frh-td with cluster overview UI being broken.

**Comment by suikast42** [comment]
The same here

**Comment by ttys3** [comment]
> Hi folks,
> 
> We understand the frustration around this issue. I’d like to apologize on behalf of our team. This was a miss on our part. We acknowledge that these types of regressions are unacceptable and are taking steps to minimize the possibility of such regressions in the future.
> 
> We be publishing a patch release next week which will address these issues. The patch releases will be available no later than March 9th.

1.15.1 still broken.

isHTMLSafe error on "overview", "Intentions" and "Peers" pages.

your guys did not do tests and wait 2 weeks release a broken patched program ?

you need 1.15.2

**Comment by sid-6581** [comment]
It's quite impressive that nobody at hashicorp even bothered to click on the pages mentioned in this very issue, for weeks, before releasing another broken build after already having egg on their face. Not sure what kind of QA you have going on over there, but at my company that doesn't fly.

It's not like this is some edge case that only happens to certain people some of the time, this is something that is completely broken for everyone, and was *known* to be broken before the new version was released.

**Comment by andrecp** [comment]
@blake  this is still broken in the main page

**Comment by ashleykleynhans** [comment]
Confirmed this is fixed in Consul 1.15.2.

**Comment by yinyu985** [comment]
My consul cluster overview empty also appeared🥲
I upgraded to 1.15.2 on purpose🤨

**Comment by david-yu** [comment]
Closing as the issue is now resolved in 1.15.2.
