### ISSUE TITLE
Build is broken for tags 0.6.1 and 0.6.2

### ISSUE THREAD

**Issue by Shinzu** [hashicorp/consul#1605]
Hello,

if i try to build consul from the source (checkout one of these tags) i get following error message:

    ==> Getting dependencies...
    # github.com/hashicorp/consul/command/agent
    command/agent/command.go:677: not enough arguments in call to reap.ReapChildren

i build with go 1.5.3.

It seems that is already fixed in the source but not for these two tags.

Greetings

**Comment by slackpad** [comment]
Hi @Shinzu we made a non backwards compatible change to the go-reap library since we found a subtle way that it could cause race conditions. If you sync github.com/hashicorp/go-reap in your `GOPATH` back to e300e334a8de28a7931fc05331345f9e985128de things should start building again.

We haven't fully integrated `godep` yet, but you can find the required dependency versions for each tag in here: https://github.com/hashicorp/consul/tree/master/deps.
