### ISSUE TITLE
Can't build master with go1.10

### ISSUE THREAD

**Issue by nitsh** [hashicorp/consul#6717]
#### Overview of the Issue

According to Contributing guidelines, we should be able to build with go1.10+ (https://github.com/hashicorp/consul/blob/master/.github/CONTRIBUTING.md#building-consul)

But the current master can't be built with g1.10+

#### Reproduction Steps

Steps to reproduce this issue, eg:

```
➜  consul git:(master) go version
go version go1.10.3 darwin/amd64
➜  consul git:(master) make dev
--> Making [GH-xxxx] references clickable...
==> Building Consul - OSes: darwin, Architectures: amd64
Building sequentially with go install
--->   darwin/amd64
# github.com/hashicorp/consul/agent/connect
agent/connect/parsing.go:205:6: undefined: strings.ReplaceAll
ERROR: Failed to build Consul for darwin/amd64
make: *** [dev-build] Error 1
```
Maybe the contributing guide should be updated?

**Comment by alvin-huang** [comment]
Thanks for the report! You are absolutely right. `strings.ReplaceAll` was added in Go 1.12 so I have updated the `CONTRIBUTING.md` to reflect this in #6723
