### ISSUE TITLE
go get github.com/hashicorp/consul@v1.7.12

### ISSUE THREAD

**Issue by guyb27** [hashicorp/consul#9832]
#### Overview of the Issue

Hello,
I'm newbie in go,
I have to debug an App,
and I have to build with the consul module
Do you have a solution please ?
![consul_issue](https://user-images.githubusercontent.com/29309816/109177872-8c6ad000-7788-11eb-9c72-0d361ab78466.PNG)

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. go get github.com/hashicorp/consul@v1.7.12

### Command return

```
go: downloading github.com/Microsoft/go-winio v0.4.
github.com/hashicorp/consul imports
github.com/hashicorp/consul/command imports
github.com/hashicorp/consul/command/agent imports
github.com/hashicorp/consul/agent imports
github.com/hashicorp/go-discover imports
github.com/hashicorp/go-discover/provider/gce imports
google.golang.org/api/compute/v1 imports
google.golang.org/api/option imports
google.golang.org/api/internal imports
google.golang.org/grpc/naming: cannot find module providing package google.golang.org/grpc/naming
```

### Operating system and Environment details

I'm working in Ubuntu 18.04.5 LTS
go version go1.16 linux/amd64

**Comment by jsosulska** [comment]
Hi there @guyb27 ,

Thank you for your question, and welcome to developing with Go! I recommend posting this question in Discuss, as well as a little bit about the application you are trying to create. The whole Consul codebase should not need to be imported. Our public [`consul-api` package](https://pkg.go.dev/github.com/hashicorp/consul/api) should be enough to suit your needs, and is much lighter weight.

I will close this thread. For further questions, see our [Discuss forum](https://discuss.hashicorp.com/c/consul/29). Our very helpful community can often help where others can't!

Happy Coding

**Comment by dpkirchner** [comment]
@guyb27 Were you able to figure out this problem? I didn't see a post on the discuss forum and this is the only Google search result I could find about it.
