### ISSUE TITLE
why? compile the project，incorrect report

### ISSUE THREAD

**Issue by yunnet** [hashicorp/consul#3756]
Why do I compile the project will be missing command.Map

$make dev
--> Making [GH-xxxx] references clickable...
--> Formatting vendor/vendor.json
test -x /mnt/e/go-src/bin/vendorfmt || go get -u github.com/magiconair/vendorfmt/cmd/vendorfmt
vendorfmt
Formatted vendor/vendor.json
--> Building consul
mkdir -p pkg/linux_amd64/ bin/
go install -ldflags '-X github.com/hashicorp/consul/version.GitCommit=a86d11e+CHANGES -X github.com/hashicorp/consul/version.GitDescribe=v1.0.2-9-ga86d11e' -tags ''
$/work-go/consul
./main.go:38: undefined: command.Map
GNUmakefile:37: recipe for target 'dev-build' failed
make: *** [dev-build] Error 2

**Comment by slackpad** [comment]
Hi @yunnet that's defined in https://github.com/hashicorp/consul/blob/master/command/registry.go, it looks like maybe you don't have a clean checkout? That was added pretty recently so I'd double check you didn't get any bad merges into your source tree if you have a fork, since things got moved around. Hope that helps!

**Comment by yunnet** [comment]
Thank you.
